apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dns
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: tooling
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: cluster/tooling/dns/
    repoURL: https://github.com/NorskHelsenett/gitOps.git
    targetRevision: refactor
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
