apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-patch
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: tooling
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  sources:
    - path: cluster/tooling/argocd
      repoURL: https://github.com/NorskHelsenett/gitOps.git
      targetRevision: refactor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    - Validate=false