apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: extras
spec:
  destination:
    namespace: kyverno
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: 'https://kyverno.github.io/kyverno/'
      targetRevision: 2.7.*
      chart: kyverno
    - repoURL: 'https://kyverno.github.io/kyverno/'
      targetRevision: 2.7.2
      helm:
        values: |
          podSecurityStandard: baseline
          failurePolicy: Ignore
      chart: kyverno-policies
    - repoURL: 'https://git.local/gitea/gitOps.git'
      path: cluster/extra/kyverno/policies
      targetRevision: main
      directory:
        recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true