apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: extras
spec:
  destination:
    namespace: kyverno
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: 'https://kyverno.github.io/kyverno/'
      targetRevision: 2.7.*
      chart: kyverno
    - repoURL: 'https://kyverno.github.io/kyverno/'
      targetRevision: 2.7.2
      helm:
        values: |
          podSecurityStandard: baseline
          failurePolicy: Ignore
          policyExclude:
            disallow-capabilities:
              any:
              - resources:
                  namespaces:
                  - argocd
                  - cert-manager
                  - default
                  - drone
                  - gitea
                  - ingress
                  - kube-node-lease
                  - kube-public
                  - kube-system
                  - kyverno
                  - vault
            disallow-host-namespaces:
              any:
              - resources:
                  namespaces:
                  - argocd
                  - cert-manager
                  - default
                  - drone
                  - gitea
                  - ingress
                  - kube-node-lease
                  - kube-public
                  - kube-system
                  - kyverno
                  - vault
            disallow-host-path:
              any:
              - resources:
                  namespaces:
                  - argocd
                  - cert-manager
                  - default
                  - drone
                  - gitea
                  - ingress
                  - kube-node-lease
                  - kube-public
                  - kube-system
                  - kyverno
                  - vault
            disallow-host-ports:
              any:
              - resources:
                  namespaces:
                  - argocd
                  - cert-manager
                  - default
                  - drone
                  - gitea
                  - ingress
                  - kube-node-lease
                  - kube-public
                  - kube-system
                  - kyverno
                  - vault
            disallow-host-process:
              any:
              - resources:
                  namespaces:
                  - argocd
                  - cert-manager
                  - default
                  - drone
                  - gitea
                  - ingress
                  - kube-node-lease
                  - kube-public
                  - kube-system
                  - kyverno
                  - vault
            disallow-privileged-containers:
              any:
              - resources:
                  namespaces:
                  - argocd
                  - cert-manager
                  - default
                  - drone
                  - gitea
                  - ingress
                  - kube-node-lease
                  - kube-public
                  - kube-system
                  - kyverno
                  - vault
            disallow-proc-mount:
              any:
              - resources:
                  namespaces:
                  - argocd
                  - cert-manager
                  - default
                  - drone
                  - gitea
                  - ingress
                  - kube-node-lease
                  - kube-public
                  - kube-system
                  - kyverno
                  - vault
            disallow-selinux:
              any:
              - resources:
                  namespaces:
                  - argocd
                  - cert-manager
                  - default
                  - drone
                  - gitea
                  - ingress
                  - kube-node-lease
                  - kube-public
                  - kube-system
                  - kyverno
                  - vault
            restrict-apparmor-profiles:
              any:
              - resources:
                  namespaces:
                  - argocd
                  - cert-manager
                  - default
                  - drone
                  - gitea
                  - ingress
                  - kube-node-lease
                  - kube-public
                  - kube-system
                  - kyverno
                  - vault
            restrict-seccomp:
              any:
              - resources:
                  namespaces:
                  - argocd
                  - cert-manager
                  - default
                  - drone
                  - gitea
                  - ingress
                  - kube-node-lease
                  - kube-public
                  - kube-system
                  - kyverno
                  - vault
            restrict-sysctls:
              any:
              - resources:
                  namespaces:
                  - argocd
                  - cert-manager
                  - default
                  - drone
                  - gitea
                  - ingress
                  - kube-node-lease
                  - kube-public
                  - kube-system
                  - kyverno
                  - vault
      chart: kyverno-policies
    - repoURL: 'https://git.local/gitea/gitOps.git'
      path: cluster/extras/kyverno/policies
      targetRevision: main
      directory:
        recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true