apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nyan
  namespace: argocd
  labels:
    app.kubernetes.io/name: nyan
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: nyan
spec:
  destination:
    namespace: nyan
    server: 'https://kubernetes.default.svc'
  source:
    path: cluster/project/nyan/
    repoURL: 'https://github.com/jonasbg/gitOps-intro.git'
    targetRevision: static-site
    directory:
      recurse: true
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
