apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-sso
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: tooling
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  sources:
    - path: cluster/local/argocd
      repoURL: https://git.local/gitea/gitOps.git
      targetRevision: refactor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Validate=false
