apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  sources:
    - path: cluster/tooling/
      repoURL: 'https://github.com/NorskHelsenett/gitOps.git'
      targetRevision: main
      directory:
        recurse: true
    - path: cluster/
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Validate=false