apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: self-signed-ca
  namespace: cert-manager
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: self-signed
  namespace: cert-manager
spec:
  ca:
    secretName: self-signed-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: self-signed
  namespace: cert-manager
spec:
  isCA: true
  commonName: svc.cluster.local
  secretName: self-signed-ca
  duration: 45000h0m0s
  privateKey:
    rotationPolicy: Always
    size: 4096
  subject:
    countries:
    - "NO"
    localities:
    - Trondheim
    organizationalUnits:
    - NHN
    organizations:
    - Norsk helsenett
  usages:
    - server auth
    - client auth
  dnsNames:
    - git.local
    - nyan.local
    - argocd.local
    - "*.local"
  issuerRef:
    name: self-signed-ca
    kind: ClusterIssuer
