apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: extras
spec:
  destination:
    namespace: vault
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: vault
    helm:
      values: |
        injector:
          enabled: true
          replicas: 1
        server:
          enabled: true
          logFormat: "json"
          ingress:
            enabled: true
            annotations: |
              cert-manager.io/cluster-issuer: self-signed
            pathType: ImplementationSpecific
            hosts:
              - host: vault.local
            tls:
            - hosts:
              - vault.local
              secretName: tls-secret
          volumes:
            - secret:
                secretName: tls-secret
              name: domain-ca
          volumeMounts:
            - mountPath: /etc/ssl/certs/ca.crt
              name: domain-ca
              readOnly: true
              subPath: ca.crt
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.23.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
      - .webhooks[]?.clientConfig.caBundle