# kubectl create secret generic drone-secrets -n drone \
# --from-literal=DRONE_GITEA_CLIENT_ID= \
# --from-literal=DRONE_GITEA_CLIENT_SECRET=
apiVersion: v1
kind: Secret
metadata:
  name: drone-secrets
  namespace: drone
type: Opaque
stringData:
  DRONE_GITEA_CLIENT_ID: #CHANGE IN GITEA.LOCAL
  DRONE_GITEA_CLIENT_SECRET: #CHANGE IN GITEA.LOCAL
