apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tooling
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: tooling
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  sources:
    - path: cluster/tooling
      repoURL: https://github.com/NorskHelsenett/gitOps.git
      targetRevision: refactor
      directory:
        recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Validate=false
