apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  sources:
    - path: cluster/project/cert-manager
      repoURL: https://github.com/NorskHelsenett/gitOps.git
      targetRevision: refactor
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    - Validate=false