apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-patch
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: cluster/project/argocd-patch
    repoURL: https://git.local/gitea/gitOps.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    - Validate=false