apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multi-juicer
  namespace: argocd
spec:
  project: default
  sources:
    - path: cluster/extras/multijuicer/addons
      repoURL: 'https://git.local/gitea/gitOps.git'
      targetRevision: main
    - repoURL: 'https://github.com/juice-shop/multi-juicer.git'
      path: helm/multi-juicer
      targetRevision: HEAD
      helm:
        values: |-
          ingress:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: self-signed
            hosts:
              - host: ctf.local
                paths:
                  - /
            tls:
              - secretName: juiceshop-tls-secret
                hosts:
                  - ctf.local
          balancer:
            replicas: 1
            service:
              type: NodePort
            cookie:
              cookieParserSecret: "THIS_IS_A_EXAMPLE_DONT_USE_THIS_AS_THE_ACTUAL_SECRET"
              secure: true
            metrics:
              basicAuth:
                password: "ROTATE_THIS_YOU_LAZY_ASS"
            podSecurityContext:
              runAsNonRoot: true
            resources:
              requests:
                cpu: 40m
                memory: 128Mi
          juiceShop:
            maxInstances: 25
            nodeEnv: "ctf"
            ctfKey: "DONT_LET_ME_FIND_YOU_USING_THIS_EXACT_VALUE"
            podSecurityContext:
              runAsNonRoot: true
              seccompProfile:
                type: RuntimeDefault
            containerSecurityContext:
              runAsNonRoot: true
              runAsUser: 65532
              runAsGroup: 0
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
            resources:
              requests:
                cpu: 15m
                memory: 56Mi
          progressWatchdog:
            securityContext:
              runAsNonRoot: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: juiceshop
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
